# Generated by Django 2.1 on 2019-08-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20190823_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='observacao',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
