# Generated by Django 2.1 on 2019-08-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20190823_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='observacao',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
