# Generated by Django 2.1 on 2019-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='adicionais',
            field=models.ManyToManyField(blank=True, to='pedidos.Adicional'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(blank=True, through='pedidos.ItemPedido', to='pedidos.Produto'),
        ),
    ]
